//xeus 전역 설정 정보....

var isOuterUser = "N";

//xeusCCTV.VIDEO_GRID_COLS
//cctv 영상수신 websocket url
//실서버
//var VIDEO_WEBSOCKET_URL ='ws://10.159.1.191/xeus-gate/stream';
//로컬
var VIDEO_WEBSOCKET_URL ='ws://10.1.74.120:28080/xeus-gate/stream';

var VIDEO_POPUP_PLAYER_LIMIT = 3;

//default animation delay
var ANI_DELAY = 250;
var ANI_DELAY_FAST = 100;
//cctv 모니터링 서브메뉴 사이즈
var CCTV_BTN_CCTV_SCH_WEST_SIZE = 450;
var CCTV_BTN_LGD_MNG_WEST_SIZE = 450;
var CCTV_BTN_PTR_VIEW_WEST_SIZE = 450;
var CCTV_BTN_FCS_VIEW_WEST_SIZE = 450;
var CCTV_BTN_PRB_CAR_WEST_SIZE = 450;

var CCTV_BTN_PTR_VIEW_EAST_SIZE = 600;
var CCTV_BTN_FCS_VIEW_EAST_SIZE = 600;
var CCTV_BTN_CCTV_MNG_EAST_SIZE = 600;
var CCTV_BTN_CCTV_PRST_EAST_SIZE = 600;
var CCTV_BTN_PRB_CAR_EAST_SIZE = 600;

//이벤트 모니터링 서브메뉴 사이즈
var EVNT_BTN_MONITOR_VIEW_WEST_SIZE = 750
var EVNT_BTN_BELL_VIEW_WEST_SIZE = 450;
var EVNT_BTN_SAFE_VIEW_WEST_SIZE = 450;
var EVNT_BTN_CAR_VIEW_WEST_SIZE = 450;
var EVNT_BTN_SOUND_VIEW_WEST_SIZE = 450;
var EVNT_BTN_EVTLOG_VIEW_WEST_SIZE = 700;
var CCTV_BTN_CCTV_PRV_WEST_SIZE = 450;

var EVNT_BTN_DISASTER_VIEW_WEST_SIZE = 800;
var EVNT_BTN_112REC_VIEW_WEST_SIZE = 800;
var EVNT_BTN_112STAT_VIEW_WEST_SIZE = 900;

//빅데이터분석 서브메뉴 사이즈
var EVNT_BTN_BIGDATA_VIEW_WEST_SIZE = 350;
var EVNT_BTN_BIGDATA_HIST_VIEW_WEST_SIZE = 900;
var CCTV_BTN_BIGDATA_RESULT_EAST_SIZE = 400;

//장비관리(NMS) 서브메뉴 사이즈
var NMS_BTN_NMG_MONITOR_VIEW_WEST_SIZE = 650;
var NMS_BTN_CHECK_REG_VIEW_WEST_SIZE = 450;
var NMS_BTN_CHECK_LIST_VIEW_WEST_SIZE = -1;
var NMS_BTN_MOBILE_LIST_VIEW_WEST_SIZE = 700;
var NMS_BTN_SITE_VIEW_WEST_SIZE = 1100;
var NMS_BTN_INFRA_VIEW_WEST_SIZE = 550;
var NMS_BTN_CABLE_VIEW_WEST_SIZE = 450;
var NMS_BTN_NMS_VIEW_WEST_SIZE = 450;
var NMS_BTN_FNMS_VIEW_WEST_SIZE = 450;

//장비관리(NMS) 서브메뉴 사이즈
var SEND_BTN_SMS_VIEW_WEST_SIZE = 550;
var SEND_BTN_VOICE_REG_VIEW_WEST_SIZE = 450;
var SEND_BTN_HIST_LIST_VIEW_WEST_SIZE = 450;

//장비관리(NMS) 서브메뉴 사이즈
var NDPS_BTN_VIEW_WEST_SIZE = 450;

//영상반출 서브메뉴 사이즈
var TVIUS_BTN_CCTV_SCH_WEST_SIZE = 450;/* 171214 : 350 -> 450 사이즈 수정*/
var TVIUS_BTN_LGD_MNG_WEST_SIZE = 450;
var TVIUS_BTN_TVIUS_REG_WEST_SIZE = 850;/* 180123 : 750 -> 850 사이즈 수정*/
var TVIUS_BTN_TVIUS_VIEW_WEST_SIZE = -1;
var TVIUS_BTN_EXT_VIEW_WEST_SIZE = -1;
var TVIUS_BTN_EVI_VIEW_WEST_SIZE = 750;
var TVIUS_BTN_TVIUS_URGENT_REG_WEST_SIZE = 850;
var TVIUS_BTN_TVIUS_HEAT_WEST_SIZE = 500;
var TVIUS_BTN_TVIUS_CAR_SCH_WEST_SIZE = 450;